import { describe, expect, it } from "vitest";

import { SEED_CARPARK_ID_LIST, SEED_CARPARK_IDS, SEED_CARPARK_NAMES } from "../src/carparks";

describe("seed carpark list", () => {
  it("still contains all 10 original T1-validated seed carpark IDs (regression -- coverage expansion must never drop them)", () => {
    const originalSeeds = ["1", "2", "3", "11", "13", "15", "16", "21", "24", "50"];
    const actual = new Set(SEED_CARPARK_ID_LIST);
    for (const id of originalSeeds) {
      expect(actual.has(id)).toBe(true);
    }
  });

  it("has no duplicate IDs and matches the current coverage-expansion state (generated by scripts/regen_seed_lists.py)", () => {
    expect(new Set(SEED_CARPARK_ID_LIST).size).toBe(SEED_CARPARK_ID_LIST.length);
    expect(SEED_CARPARK_ID_LIST.length).toBeGreaterThanOrEqual(10);
  });

  it("keeps SEED_CARPARK_IDS and SEED_CARPARK_NAMES in sync with the ID list", () => {
    for (const id of SEED_CARPARK_ID_LIST) {
      expect(SEED_CARPARK_IDS.has(id)).toBe(true);
      expect(SEED_CARPARK_NAMES[id]).toBeTruthy();
    }
    expect(SEED_CARPARK_IDS.size).toBe(SEED_CARPARK_ID_LIST.length);
  });
});
