// Static, client-side seed list of supported carparks (10 original T1-validated
// seeds plus verified coverage-expansion candidates). Powers search (no network
// involved) and doubles as the share-link whitelist (design doc Security
// section: "the frontend validates the carpark_id from a share-link URL
// against the same whitelist client-side"). Generated by
// scripts/regen_seed_lists.py from data/carpark_coverage_map.json -- do not
// hand-edit the SEED_CARPARKS array, re-run the generator instead. Must match
// db/schema.sql's carparks table (server-side canonical copy).

export interface SeedCarpark {
  id: string;
  name: string;
}

export const SEED_CARPARKS: readonly SeedCarpark[] = [
  { id: "1", name: "Suntec City" },
  { id: "2", name: "Marina Square" },
  { id: "3", name: "Raffles City" },
  { id: "5", name: "Millenia Singapore" },
  { id: "7", name: "Orchard Point" },
  { id: "8", name: "The Heeren" },
  { id: "9", name: "Plaza Singapura" },
  { id: "10", name: "The Cathay" },
  { id: "11", name: "Cineleisure" },
  { id: "13", name: "Ngee Ann City" },
  { id: "14", name: "Wisma Atria" },
  { id: "15", name: "Wheelock Place" },
  { id: "16", name: "VivoCity P3" },
  { id: "19", name: "Harbourfront Centre" },
  { id: "20", name: "Far East Plaza" },
  { id: "21", name: "Centrepoint" },
  { id: "23", name: "ION Orchard" },
  { id: "24", name: "313@Somerset" },
  { id: "27", name: "Orchard Central" },
  { id: "43", name: "Westgate" },
  { id: "50", name: "VivoCity P2" },
  { id: "53", name: "IMM Building" },
  { id: "63", name: "Tampines Mall" },
  { id: "65", name: "Bedok Mall" },
];

const SEED_CARPARK_IDS: ReadonlySet<string> = new Set(SEED_CARPARKS.map((c) => c.id));

/** Client-side whitelist check -- used for share-link validation (Security). */
export function isKnownCarparkId(id: string): boolean {
  return SEED_CARPARK_IDS.has(id);
}

export function getSeedCarparkById(id: string): SeedCarpark | undefined {
  return SEED_CARPARKS.find((c) => c.id === id);
}

/** Live-filter-as-you-type search against the static list (Design Details). */
export function searchSeedCarparks(query: string): SeedCarpark[] {
  const normalized = query.trim().toLowerCase();
  if (normalized === "") return [];
  return SEED_CARPARKS.filter((c) => c.name.toLowerCase().includes(normalized));
}
