// The 10 T1-validated original seed carparks plus verified coverage-expansion
// candidates (generated by scripts/regen_seed_lists.py from
// data/carpark_coverage_map.json -- do not hand-edit, re-run the generator
// instead). Mirrors the db/schema.sql seed rows plus later carparks INSERTs;
// LTA CarParkIDs are strings.

export const SEED_CARPARK_NAMES: Readonly<Record<string, string>> = {
  "1": "Suntec City",
  "2": "Marina Square",
  "3": "Raffles City",
  "5": "Millenia Singapore",
  "7": "Orchard Point",
  "8": "The Heeren",
  "9": "Plaza Singapura",
  "10": "The Cathay",
  "11": "Cineleisure",
  "13": "Ngee Ann City",
  "14": "Wisma Atria",
  "15": "Wheelock Place",
  "16": "VivoCity P3",
  "19": "Harbourfront Centre",
  "20": "Far East Plaza",
  "21": "Centrepoint",
  "23": "ION Orchard",
  "24": "313@Somerset",
  "27": "Orchard Central",
  "43": "Westgate",
  "50": "VivoCity P2",
  "53": "IMM Building",
  "63": "Tampines Mall",
  "65": "Bedok Mall",
};

export const SEED_CARPARK_ID_LIST: readonly string[] = Object.keys(SEED_CARPARK_NAMES);

export const SEED_CARPARK_IDS: ReadonlySet<string> = new Set(SEED_CARPARK_ID_LIST);
